theme = "hugo-theme-learn"
baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
publishDir = "public"
relativeurls = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "red"