theme = "hugo-theme-learn"
author = "Tyler Grant Smith"
#disableSearch = true
baseURL = ""
languageCode = "en-us"
title = "2019 Exam 9"
publishDir = "public"
#relativeurls = true
#ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "red"